export const DesktopProjectHighLights = [
    {
        id: 'Thuocsi',
        title: 'Thuocsi - B2B Medical E-Commerce',
        description: 'Streamlining medical supply procurement for businesses with a trusted e-commerce platform.',
        img: '/project-highlights/tss.webp',
        isReady: false,
        href: '/project-highlights/thuocsi',
    },
    {
        id: 'Dakoli',
        title: 'Dakoli - B2B Ecommerce Platform',
        description: 'Your go-to platform for businesses and customers to shop a variety of products easily.',
        img: '/project-highlights/dk.webp',
        isReady: false,
        href: '/project-highlights/dakoli',
    },
    {
        id: 'Washup',
        title: 'Washup - Vehicle wash app',
        description: 'Quickly book nearby motorbike and car washes with ease, wherever you are.',
        img: '/project-highlights/wuu.webp',
        isReady: true,
        href: '/project-highlights/wash-up',
    },
    {
        id: 'Cloakline',
        title: 'Cloakline - VPN app',
        description: 'Experience seamless browsing with ultra-fast and stable VPN servers worldwide.',
        img: '/project-highlights/cll.webp',
        isReady: false,
        href: '/project-highlights/cloakline',
    },
    {
        id: 'Circa',
        title: 'Circa - B2C Medical Ecommerce',
        description: 'Seamlessly connect with trusted suppliers for all your medical essentials, delivered directly to you.',
        img: '/project-highlights/cc.webp',
        isReady: false,
        href: '/project-highlights/circa',
    },
    {
        id: 'CircaF',
        title: 'Circa Franchise',
        description: 'Come join with us to deliver trusted healthcare products through our e-commerce franchise.',
        img: '/project-highlights/cff.webp',
        isReady: false,
        href: '/project-highlights/circa-franchise',
    },
]

export const ProjectHighLights = [
    {
        id: 'Washup',
        title: 'Washup - Vehicle wash app',
        description: 'Quickly book nearby motorbike and car washes with ease, wherever you are.',
        img: '/project-highlights/wuu.webp',
        isReady: true,
        href: '/project-highlights/wash-up',
    },
    {
        id: 'Cloakline',
        title: 'Cloakline - VPN app',
        description: 'Experience seamless browsing with ultra-fast and stable VPN servers worldwide.',
        img: '/project-highlights/cll.webp',
        isReady: false,
        href: '/project-highlights/cloakline',
    },
    {
        id: 'Circa',
        title: 'Circa - B2C Medical Ecommerce',
        description: 'Seamlessly connect with trusted suppliers for all your medical essentials, delivered directly to you.',
        img: '/project-highlights/cc.webp',
        isReady: false,
        href: '/project-highlights/circa',
    },
    {
        id: 'CircaF',
        title: 'Circa Franchise',
        description: 'Come join with us to deliver trusted healthcare products through our e-commerce franchise.',
        img: '/project-highlights/cff.webp',
        isReady: false,
        href: '/project-highlights/circa-franchise',
    },
    {
        id: 'Thuocsi',
        title: 'Thuocsi - B2B Medical E-Commerce',
        description: 'Streamlining medical supply procurement for businesses with a trusted e-commerce platform.',
        img: '/project-highlights/tss.webp',
        isReady: false,
        href: '/project-highlights/thuocsi',
    },
    {
        id: 'Dakoli',
        title: 'Dakoli - B2B Ecommerce Platform',
        description: 'Your go-to platform for businesses and customers to shop a variety of products easily.',
        img: '/project-highlights/dk.webp',
        isReady: false,
        href: '/project-highlights/dakoli',
    },
]